import { StylishPage } from "../type";

export const en: StylishPage = {
  head: {
    title: "Stylish",
    description: "Generated by create next app",
  },
  coolStyles: "Cool Styles",
};
export default en;
