import { StylishPage } from "../type";

export const en: StylishPage = {
  head: {
    title: "Stylish",
    description: "Generated by create next app",
  },
  coolStyles: "Cool Styles",
  withHover: "With :hover",
  letsBounce: "Let's bounce",
  home: "Home",
};
export default en;
