import { useTranslation } from "next-i18next";
import Head from "next/head";
import Link from "next/link";
import styles from "./styles";

const Index = (): JSX.Element => {
  const { t } = useTranslation("home");

  return (
    <div css={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main css={styles.main}>
        <h1 css={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p css={styles.description}>
          Get started by editing <code css={styles.code}>pages/index.tsx</code>
        </p>

        <div css={styles.grid}>
          <Link href="/stylish" passHref>
            <a css={styles.card}>
              <h2>Styling &rarr;</h2>
              <p>{t("styling.description")}</p>
            </a>
          </Link>

          <a href="https://nextjs.org/docs" css={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" css={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            css={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            css={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>
    </div>
  );
};

export default Index;
