import { HomePage } from "../type";

export const de: HomePage = {
  head: {
    title: "Home",
    description: "Generated by create next app",
  },
  description: "Beginnen Sie mit der Bearbeitung `pages/index.tsx`",
  heading: "Willkommen bei Next.js!",
  cards: {
    deploy: {
      name: "Bereitstellen →",
      description:
        "Stellen Sie Ihre Next.js-Site mit Vercel sofort auf einer öffentlichen URL bereit.",
    },
    documentation: {
      name: "Dokumentation →",
      description:
        "Hier finden Sie ausführliche Informationen zu den Funktionen und APIs von Next.js.",
    },
    examples: {
      name: "Beispiele →",
      description:
        "Ermitteln und Bereitstellen von Boilerplate-Beispiel-Next.js-Projekten.",
    },
    learn: {
      name: "Lernen →",
      description:
        "Lernen Sie Next.js in einem interaktiven Kurs mit Quiz kennen!",
    },
    styling: {
      name: "Styling →",
      description: "Beispiele für das Styling mit Emotion.js",
    },
  },
};
