import { HomePage } from "../type";

export const en: HomePage = {
  head: {
    title: "Home",
    description: "Generated by create next app",
  },
  description: "Get started by editing `pages/index.tsx`",
  heading: "Welcome to Next.js!",
  cards: {
    deploy: {
      name: "Deploy →",
      description:
        "Instantly deploy your Next.js site to a public URL with Vercel.",
    },
    documentation: {
      name: "Documentation →",
      description: "Find in-depth information about Next.js features and API.",
    },
    examples: {
      name: "Examples →",
      description: "Discover and deploy boilerplate example Next.js projects.",
    },
    learn: {
      name: "Learn →",
      description: "Learn about Next.js in an interactive course with quizzes!",
    },
    styling: {
      name: "Styling →",
      description: "Examples styling using Emotion.js",
    },
  },
};
